universal containers/src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

universal containers/src/classes/WebServiceWSdemo.cls
global class WebServiceWSdemo {

	webservice static String displayMsg(String firstname,String lastname){
		return firstname+' '+lastname;
	}
	
	
	webservice static String insertCase(String firstname,String lastname,String State,String city){
		
		Candidate__c cand=new Candidate__c();
		cand.First_Name__c=firstname;
		cand.Last_Name__c=lastname;
		cand.State_Province__c=State;
		cand.City__c=city;
		try{
			Database.insert(cand);
			
		}Catch(Exception e){
			return e.getMessage();
		}
		
			return 'Insertion of Candidate object is successful and the Refernece Id is '+cand.Id;
		
	}
}