universal containers/src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

universal containers/src/classes/CandidateEmailBC.cls
/**
 * Email services are automated processes that use Apex classes
 * to process the contents, headers, and attachments of inbound
 * email.
 */
global class CandidateEmailBC implements Messaging.InboundEmailHandler {

    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();

		String emailbdy=EncodingUtil.urlDecode(email.plaintextbody, 'UTF-8');
		String[] emailtxt=emailbdy.split(';');
		Candidate__c nc=new Candidate__c();
		nc.first_Name__c=emailtxt[0];
		nc.last_name__c=emailtxt[1];
		nc.email__c=emailtxt[2];
		
		try{
			Database.Insert(nc);
			result.success=true;
		}Catch(Exception e){
		
		System.debug('The exception e is '+e.getMessage());
		result.success=false;
		}
        return result;
    }
    
    
}