universal containers/src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Max_Pay__c</fullName>
        <label>Max Pay</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Pay__c</fullName>
        <label>Min Pay</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

universal containers/src/classes/Offers2.cls
public  class Offers2 {
    
    public static void checkoffer(List<Offer__c> offers1){
        
        for(Offer__c o:offers1){
          Position__c p= [Select min_pay__c, max_pay__c from Position__c where id in (select position__c from job_application__c where id=:o.job_application__c) Limit 1 ];
          if(o.Actual_Salary__c<p.min_pay__c || o.Actual_Salary__c>p.max_pay__c){
            
            o.addError('Actual salary is not between the min pay and max pay');
          }
        }
    }

}