universal containers/src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Average_Pay_Scale__c</fullName>
        <label>Average Pay Scale</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hello__c</fullName>
        <label>Hello</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Pay__c</fullName>
        <label>Max Pay</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Pay__c</fullName>
        <label>Min Pay</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

universal containers/src/classes/HelloWorldPositionClass.cls
public class HelloWorldPositionClass {
    
    public static void helloWorld(List<Position__c> positions){
        
        for (Position__c p:positions){
            if (p.Hello__c != 'World') {
                p.Hello__c = 'World'; 
            }
        }
    }
    
      public static void average(List<Position__c> positions){
        
        for (Position__c p:positions){
            if (p.Average_Pay_Scale__c ==null) {
                p.Average_Pay_Scale__c =p.Max_Pay__c-p.Min_Pay__c ; 
            }
        }
    }
    
    
  
}