universal containers/src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Max_Pay__c</fullName>
        <label>Max Pay</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Pay__c</fullName>
        <label>Min Pay</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

universal containers/src/classes/positionCalcController.cls
public  class positionCalcController {
	
	Position__c precord;
	public double vpay{get;set;}
	public double pay{get;set;}
	public double gross{get;set;}
	ApexPages.StandardController pcont1;
	
	public positionCalcController(ApexPages.StandardController pcont){
		
		precord=(Position__c)pcont.getRecord();
		
	}
	

	public void calc(){
		
		double pay=precord.Max_Pay__c-precord.Min_Pay__c;
		vpay=pay*0.4;
		gross=pay+vpay;
	}

}