universal containers/src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <picklist>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Hiring_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hiring Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Pay__c</fullName>
        <label>Max Pay</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Pay__c</fullName>
        <label>Min Pay</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Full Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temp</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

universal containers/src/classes/PositionBC.cls
public  class PositionBC implements CalculateBC {
	
	public Integer calculateHRA(Position__c p ){
		
		if(p.type__c=='temp'){
			
			  return Integer.valueOf(0.2*(p.Max_Pay__c-p.Min_Pay__c));
		}
		return Integer.valueOf(0.3*(p.Max_Pay__c-p.Min_Pay__c));
	}
	
	public Double calculatePremium(Position__c p ){
		if(p.type__c=='temp'){
			
			  return Integer.valueOf(0.2*(p.Max_Pay__c-p.Min_Pay__c));
		}
		return Integer.valueOf(0.15*(p.Max_Pay__c-p.Min_Pay__c));
	}
	
    public static void checkPosition(List<Position__c> positions){
    	
    	for(Position__C p:positions){
    		
    		if(p.department__c == 'Engineering' || p.department__c == 'IT'){
    			if(p.type__c == 'Temp'){
    				p.addError('Cannot have temporary positions in tehnical departments');
    			}
    		}
    	}
    	
    }
    
    public static void checkpayScale(list<Position__c>newlist,list<Position__c>oldlist){
    	
    	for(Position__c p:newlist){
    		for(Position__c p1:oldlist){
    			if(p.Min_Pay__c<p1.Min_Pay__c || p.max_pay__c<p1.max_pay__c){
    				p.addError('Pay Scale must be edited to higher ');
    			}
    		}
    	}
    } 


public static void subscribe(List<Position__c> plist){
	
	list<EntitySubscription> es=new list<EntitySubscription>();
	
	for(Position__c p:plist){
		
		EntitySubscription e=new EntitySubscription();
		e.subscriberId=p.hiring_manager__c;
		e.ParentId=p.Id;
		es.add(e);
	}
	
	Database.Insert(es);
}

public static void sharerecord(List<Position__c>plist){
	
	List<Position__share> sharelist=new List<Position__share>();
	for(Position__c p:pList){
		
		Position__share ps=new Position__share();
		
		ps.parentID=p.Id;
		ps.userOrGroupID=p.hiring_manager__c;
		ps.accessLevel='Edit';
		ps.RowCause=Position__share.RowCause.Supervisor__c;
		
		shareList.add(ps);
	}
	
	Database.Insert(shareList);
}

public static void publishRecords(List<Position__c>plist){

	CollaborationGroup cg=[Select id from CollaborationGroup where name='manager' Limit 1];	
	List<FeedItem>flist=new List<FeedItem>();
	
	for(position__c p:plist){
		if(p.status__c=='Open' || p.status__c=='closed'){
		FeedItem fi=new FeedItem();
		fi.parentID=cg.id;
		fi.title='Positioned Opened please nominate';
		fi.body='Send Resumes for position';
		fi.linkurl='/'+p.id;
		flist.add(fi);
	 }
	}
	Database.Insert(flist);
	
}


}